sudo: required
services:
  - docker

before_install:
  - docker build -t dockerlearn -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerlearn npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "dockerlearn"
  env: "Dockerlearn-env"
  bucket_name: "elasticbeanstalk-ap-south-1-214413824643"
  bucket_path: "dockerlearn"
  on:
    branch: master
